export const UK_LOCAL_AUTHORITIES = [
  // ENGLAND — Metropolitan Districts
  { value: "Barnsley Borough Council", label: "Barnsley Borough Council", group: "England — Metropolitan Districts" },
  { value: "Birmingham City Council", label: "Birmingham City Council", group: "England — Metropolitan Districts" },
  { value: "Bolton Borough Council", label: "Bolton Borough Council", group: "England — Metropolitan Districts" },
  { value: "Bradford City Council", label: "Bradford City Council", group: "England — Metropolitan Districts" },
  { value: "Bury Borough Council", label: "Bury Borough Council", group: "England — Metropolitan Districts" },
  { value: "Calderdale Borough Council", label: "Calderdale Borough Council", group: "England — Metropolitan Districts" },
  { value: "Coventry City Council", label: "Coventry City Council", group: "England — Metropolitan Districts" },
  { value: "Doncaster Borough Council", label: "Doncaster Borough Council", group: "England — Metropolitan Districts" },
  { value: "Dudley Borough Council", label: "Dudley Borough Council", group: "England — Metropolitan Districts" },
  { value: "Gateshead Borough Council", label: "Gateshead Borough Council", group: "England — Metropolitan Districts" },
  { value: "Kirklees Borough Council", label: "Kirklees Borough Council", group: "England — Metropolitan Districts" },
  { value: "Knowsley Borough Council", label: "Knowsley Borough Council", group: "England — Metropolitan Districts" },
  { value: "Leeds City Council", label: "Leeds City Council", group: "England — Metropolitan Districts" },
  { value: "Liverpool City Council", label: "Liverpool City Council", group: "England — Metropolitan Districts" },
  { value: "Manchester City Council", label: "Manchester City Council", group: "England — Metropolitan Districts" },
  { value: "Newcastle Upon Tyne City Council", label: "Newcastle Upon Tyne City Council", group: "England — Metropolitan Districts" },
  { value: "North Tyneside Borough Council", label: "North Tyneside Borough Council", group: "England — Metropolitan Districts" },
  { value: "Oldham Borough Council", label: "Oldham Borough Council", group: "England — Metropolitan Districts" },
  { value: "Rochdale Borough Council", label: "Rochdale Borough Council", group: "England — Metropolitan Districts" },
  { value: "Rotherham Borough Council", label: "Rotherham Borough Council", group: "England — Metropolitan Districts" },
  { value: "Salford City Council", label: "Salford City Council", group: "England — Metropolitan Districts" },
  { value: "Sandwell Borough Council", label: "Sandwell Borough Council", group: "England — Metropolitan Districts" },
  { value: "Sefton Borough Council", label: "Sefton Borough Council", group: "England — Metropolitan Districts" },
  { value: "Sheffield City Council", label: "Sheffield City Council", group: "England — Metropolitan Districts" },
  { value: "Solihull Borough Council", label: "Solihull Borough Council", group: "England — Metropolitan Districts" },
  { value: "South Tyneside Borough Council", label: "South Tyneside Borough Council", group: "England — Metropolitan Districts" },
  { value: "St Helens Borough Council", label: "St Helens Borough Council", group: "England — Metropolitan Districts" },
  { value: "Stockport Borough Council", label: "Stockport Borough Council", group: "England — Metropolitan Districts" },
  { value: "Sunderland City Council", label: "Sunderland City Council", group: "England — Metropolitan Districts" },
  { value: "Tameside Borough Council", label: "Tameside Borough Council", group: "England — Metropolitan Districts" },
  { value: "Trafford Borough Council", label: "Trafford Borough Council", group: "England — Metropolitan Districts" },
  { value: "Wakefield City Council", label: "Wakefield City Council", group: "England — Metropolitan Districts" },
  { value: "Walsall Borough Council", label: "Walsall Borough Council", group: "England — Metropolitan Districts" },
  { value: "Wigan Borough Council", label: "Wigan Borough Council", group: "England — Metropolitan Districts" },
  { value: "Wirral Borough Council", label: "Wirral Borough Council", group: "England — Metropolitan Districts" },
  { value: "Wolverhampton City Council", label: "Wolverhampton City Council", group: "England — Metropolitan Districts" },
  // ENGLAND — London Boroughs
  { value: "Barking and Dagenham", label: "Barking and Dagenham", group: "England — London Boroughs" },
  { value: "Barnet", label: "Barnet", group: "England — London Boroughs" },
  { value: "Bexley", label: "Bexley", group: "England — London Boroughs" },
  { value: "Brent", label: "Brent", group: "England — London Boroughs" },
  { value: "Bromley", label: "Bromley", group: "England — London Boroughs" },
  { value: "Camden", label: "Camden", group: "England — London Boroughs" },
  { value: "City of London", label: "City of London", group: "England — London Boroughs" },
  { value: "Croydon", label: "Croydon", group: "England — London Boroughs" },
  { value: "Ealing", label: "Ealing", group: "England — London Boroughs" },
  { value: "Enfield", label: "Enfield", group: "England — London Boroughs" },
  { value: "Greenwich", label: "Greenwich", group: "England — London Boroughs" },
  { value: "Hackney", label: "Hackney", group: "England — London Boroughs" },
  { value: "Hammersmith and Fulham", label: "Hammersmith and Fulham", group: "England — London Boroughs" },
  { value: "Haringey", label: "Haringey", group: "England — London Boroughs" },
  { value: "Harrow", label: "Harrow", group: "England — London Boroughs" },
  { value: "Havering", label: "Havering", group: "England — London Boroughs" },
  { value: "Hillingdon", label: "Hillingdon", group: "England — London Boroughs" },
  { value: "Hounslow", label: "Hounslow", group: "England — London Boroughs" },
  { value: "Islington", label: "Islington", group: "England — London Boroughs" },
  { value: "Kensington and Chelsea", label: "Kensington and Chelsea", group: "England — London Boroughs" },
  { value: "Kingston upon Thames", label: "Kingston upon Thames", group: "England — London Boroughs" },
  { value: "Lambeth", label: "Lambeth", group: "England — London Boroughs" },
  { value: "Lewisham", label: "Lewisham", group: "England — London Boroughs" },
  { value: "Merton", label: "Merton", group: "England — London Boroughs" },
  { value: "Newham", label: "Newham", group: "England — London Boroughs" },
  { value: "Redbridge", label: "Redbridge", group: "England — London Boroughs" },
  { value: "Richmond upon Thames", label: "Richmond upon Thames", group: "England — London Boroughs" },
  { value: "Southwark", label: "Southwark", group: "England — London Boroughs" },
  { value: "Sutton", label: "Sutton", group: "England — London Boroughs" },
  { value: "Tower Hamlets", label: "Tower Hamlets", group: "England — London Boroughs" },
  { value: "Waltham Forest", label: "Waltham Forest", group: "England — London Boroughs" },
  { value: "Wandsworth", label: "Wandsworth", group: "England — London Boroughs" },
  { value: "Westminster", label: "Westminster", group: "England — London Boroughs" },
  // ENGLAND — Unitary Authorities
  { value: "Bath and North East Somerset Council", label: "Bath and North East Somerset Council", group: "England — Unitary Authorities" },
  { value: "Bedford Borough Council", label: "Bedford Borough Council", group: "England — Unitary Authorities" },
  { value: "Blackburn with Darwen Borough Council", label: "Blackburn with Darwen Borough Council", group: "England — Unitary Authorities" },
  { value: "Blackpool Council", label: "Blackpool Council", group: "England — Unitary Authorities" },
  { value: "Bournemouth Christchurch and Poole Council", label: "Bournemouth Christchurch and Poole Council", group: "England — Unitary Authorities" },
  { value: "Bracknell Forest Borough Council", label: "Bracknell Forest Borough Council", group: "England — Unitary Authorities" },
  { value: "Brighton and Hove City Council", label: "Brighton and Hove City Council", group: "England — Unitary Authorities" },
  { value: "Bristol City Council", label: "Bristol City Council", group: "England — Unitary Authorities" },
  { value: "Buckinghamshire Council", label: "Buckinghamshire Council", group: "England — Unitary Authorities" },
  { value: "Central Bedfordshire Council", label: "Central Bedfordshire Council", group: "England — Unitary Authorities" },
  { value: "Cheshire East Council", label: "Cheshire East Council", group: "England — Unitary Authorities" },
  { value: "Cheshire West and Chester Council", label: "Cheshire West and Chester Council", group: "England — Unitary Authorities" },
  { value: "Cornwall Council", label: "Cornwall Council", group: "England — Unitary Authorities" },
  { value: "Cumberland Council", label: "Cumberland Council", group: "England — Unitary Authorities" },
  { value: "Darlington Borough Council", label: "Darlington Borough Council", group: "England — Unitary Authorities" },
  { value: "Derby City Council", label: "Derby City Council", group: "England — Unitary Authorities" },
  { value: "Dorset Council", label: "Dorset Council", group: "England — Unitary Authorities" },
  { value: "Durham County Council", label: "Durham County Council", group: "England — Unitary Authorities" },
  { value: "East Riding of Yorkshire Council", label: "East Riding of Yorkshire Council", group: "England — Unitary Authorities" },
  { value: "Halton Borough Council", label: "Halton Borough Council", group: "England — Unitary Authorities" },
  { value: "Hartlepool Borough Council", label: "Hartlepool Borough Council", group: "England — Unitary Authorities" },
  { value: "Herefordshire Council", label: "Herefordshire Council", group: "England — Unitary Authorities" },
  { value: "Hull City Council", label: "Hull City Council", group: "England — Unitary Authorities" },
  { value: "Isle of Wight Council", label: "Isle of Wight Council", group: "England — Unitary Authorities" },
  { value: "Isles of Scilly Council", label: "Isles of Scilly Council", group: "England — Unitary Authorities" },
  { value: "Leicester City Council", label: "Leicester City Council", group: "England — Unitary Authorities" },
  { value: "Luton Borough Council", label: "Luton Borough Council", group: "England — Unitary Authorities" },
  { value: "Medway Council", label: "Medway Council", group: "England — Unitary Authorities" },
  { value: "Middlesbrough Borough Council", label: "Middlesbrough Borough Council", group: "England — Unitary Authorities" },
  { value: "Milton Keynes Council", label: "Milton Keynes Council", group: "England — Unitary Authorities" },
  { value: "North East Lincolnshire Council", label: "North East Lincolnshire Council", group: "England — Unitary Authorities" },
  { value: "North Lincolnshire Council", label: "North Lincolnshire Council", group: "England — Unitary Authorities" },
  { value: "North Northamptonshire Council", label: "North Northamptonshire Council", group: "England — Unitary Authorities" },
  { value: "North Somerset Council", label: "North Somerset Council", group: "England — Unitary Authorities" },
  { value: "North Yorkshire Council", label: "North Yorkshire Council", group: "England — Unitary Authorities" },
  { value: "Northumberland County Council", label: "Northumberland County Council", group: "England — Unitary Authorities" },
  { value: "Nottingham City Council", label: "Nottingham City Council", group: "England — Unitary Authorities" },
  { value: "Peterborough City Council", label: "Peterborough City Council", group: "England — Unitary Authorities" },
  { value: "Plymouth City Council", label: "Plymouth City Council", group: "England — Unitary Authorities" },
  { value: "Portsmouth City Council", label: "Portsmouth City Council", group: "England — Unitary Authorities" },
  { value: "Reading Borough Council", label: "Reading Borough Council", group: "England — Unitary Authorities" },
  { value: "Redcar and Cleveland Borough Council", label: "Redcar and Cleveland Borough Council", group: "England — Unitary Authorities" },
  { value: "Rutland County Council", label: "Rutland County Council", group: "England — Unitary Authorities" },
  { value: "Shropshire Council", label: "Shropshire Council", group: "England — Unitary Authorities" },
  { value: "Slough Borough Council", label: "Slough Borough Council", group: "England — Unitary Authorities" },
  { value: "Somerset Council", label: "Somerset Council", group: "England — Unitary Authorities" },
  { value: "Southampton City Council", label: "Southampton City Council", group: "England — Unitary Authorities" },
  { value: "Southend-on-Sea Borough Council", label: "Southend-on-Sea Borough Council", group: "England — Unitary Authorities" },
  { value: "South Gloucestershire Council", label: "South Gloucestershire Council", group: "England — Unitary Authorities" },
  { value: "Stockton-on-Tees Borough Council", label: "Stockton-on-Tees Borough Council", group: "England — Unitary Authorities" },
  { value: "Stoke-on-Trent City Council", label: "Stoke-on-Trent City Council", group: "England — Unitary Authorities" },
  { value: "Swindon Borough Council", label: "Swindon Borough Council", group: "England — Unitary Authorities" },
  { value: "Telford and Wrekin Borough Council", label: "Telford and Wrekin Borough Council", group: "England — Unitary Authorities" },
  { value: "Thurrock Council", label: "Thurrock Council", group: "England — Unitary Authorities" },
  { value: "Torbay Council", label: "Torbay Council", group: "England — Unitary Authorities" },
  { value: "Warrington Borough Council", label: "Warrington Borough Council", group: "England — Unitary Authorities" },
  { value: "West Berkshire Council", label: "West Berkshire Council", group: "England — Unitary Authorities" },
  { value: "West Northamptonshire Council", label: "West Northamptonshire Council", group: "England — Unitary Authorities" },
  { value: "Westmorland and Furness Council", label: "Westmorland and Furness Council", group: "England — Unitary Authorities" },
  { value: "Wiltshire Council", label: "Wiltshire Council", group: "England — Unitary Authorities" },
  { value: "Windsor and Maidenhead Borough Council", label: "Windsor and Maidenhead Borough Council", group: "England — Unitary Authorities" },
  { value: "Wokingham Borough Council", label: "Wokingham Borough Council", group: "England — Unitary Authorities" },
  { value: "City of York Council", label: "City of York Council", group: "England — Unitary Authorities" },
  // ENGLAND — County Councils
  { value: "Cambridgeshire County Council", label: "Cambridgeshire County Council", group: "England — County Councils" },
  { value: "Derbyshire County Council", label: "Derbyshire County Council", group: "England — County Councils" },
  { value: "Devon County Council", label: "Devon County Council", group: "England — County Councils" },
  { value: "East Sussex County Council", label: "East Sussex County Council", group: "England — County Councils" },
  { value: "Essex County Council", label: "Essex County Council", group: "England — County Councils" },
  { value: "Gloucestershire County Council", label: "Gloucestershire County Council", group: "England — County Councils" },
  { value: "Hampshire County Council", label: "Hampshire County Council", group: "England — County Councils" },
  { value: "Hertfordshire County Council", label: "Hertfordshire County Council", group: "England — County Councils" },
  { value: "Kent County Council", label: "Kent County Council", group: "England — County Councils" },
  { value: "Lancashire County Council", label: "Lancashire County Council", group: "England — County Councils" },
  { value: "Leicestershire County Council", label: "Leicestershire County Council", group: "England — County Councils" },
  { value: "Lincolnshire County Council", label: "Lincolnshire County Council", group: "England — County Councils" },
  { value: "Norfolk County Council", label: "Norfolk County Council", group: "England — County Councils" },
  { value: "Nottinghamshire County Council", label: "Nottinghamshire County Council", group: "England — County Councils" },
  { value: "Oxfordshire County Council", label: "Oxfordshire County Council", group: "England — County Councils" },
  { value: "Staffordshire County Council", label: "Staffordshire County Council", group: "England — County Councils" },
  { value: "Suffolk County Council", label: "Suffolk County Council", group: "England — County Councils" },
  { value: "Surrey County Council", label: "Surrey County Council", group: "England — County Councils" },
  { value: "Warwickshire County Council", label: "Warwickshire County Council", group: "England — County Councils" },
  { value: "West Sussex County Council", label: "West Sussex County Council", group: "England — County Councils" },
  { value: "Worcestershire County Council", label: "Worcestershire County Council", group: "England — County Councils" },
  // Wales
  { value: "Blaenau Gwent County Borough Council", label: "Blaenau Gwent County Borough Council", group: "Wales" },
  { value: "Bridgend County Borough Council", label: "Bridgend County Borough Council", group: "Wales" },
  { value: "Caerphilly County Borough Council", label: "Caerphilly County Borough Council", group: "Wales" },
  { value: "Cardiff Council", label: "Cardiff Council", group: "Wales" },
  { value: "Carmarthenshire County Council", label: "Carmarthenshire County Council", group: "Wales" },
  { value: "Ceredigion County Council", label: "Ceredigion County Council", group: "Wales" },
  { value: "Conwy County Borough Council", label: "Conwy County Borough Council", group: "Wales" },
  { value: "Denbighshire County Council", label: "Denbighshire County Council", group: "Wales" },
  { value: "Flintshire County Council", label: "Flintshire County Council", group: "Wales" },
  { value: "Gwynedd Council", label: "Gwynedd Council", group: "Wales" },
  { value: "Isle of Anglesey County Council", label: "Isle of Anglesey County Council", group: "Wales" },
  { value: "Merthyr Tydfil County Borough Council", label: "Merthyr Tydfil County Borough Council", group: "Wales" },
  { value: "Monmouthshire County Council", label: "Monmouthshire County Council", group: "Wales" },
  { value: "Neath Port Talbot County Borough Council", label: "Neath Port Talbot County Borough Council", group: "Wales" },
  { value: "Newport City Council", label: "Newport City Council", group: "Wales" },
  { value: "Pembrokeshire County Council", label: "Pembrokeshire County Council", group: "Wales" },
  { value: "Powys County Council", label: "Powys County Council", group: "Wales" },
  { value: "Rhondda Cynon Taf County Borough Council", label: "Rhondda Cynon Taf County Borough Council", group: "Wales" },
  { value: "Swansea Council", label: "Swansea Council", group: "Wales" },
  { value: "Torfaen County Borough Council", label: "Torfaen County Borough Council", group: "Wales" },
  { value: "Vale of Glamorgan Council", label: "Vale of Glamorgan Council", group: "Wales" },
  { value: "Wrexham County Borough Council", label: "Wrexham County Borough Council", group: "Wales" },
  // Scotland
  { value: "Aberdeen City Council", label: "Aberdeen City Council", group: "Scotland" },
  { value: "Aberdeenshire Council", label: "Aberdeenshire Council", group: "Scotland" },
  { value: "Angus Council", label: "Angus Council", group: "Scotland" },
  { value: "Argyll and Bute Council", label: "Argyll and Bute Council", group: "Scotland" },
  { value: "Clackmannanshire Council", label: "Clackmannanshire Council", group: "Scotland" },
  { value: "Dumfries and Galloway Council", label: "Dumfries and Galloway Council", group: "Scotland" },
  { value: "Dundee City Council", label: "Dundee City Council", group: "Scotland" },
  { value: "East Ayrshire Council", label: "East Ayrshire Council", group: "Scotland" },
  { value: "East Dunbartonshire Council", label: "East Dunbartonshire Council", group: "Scotland" },
  { value: "East Lothian Council", label: "East Lothian Council", group: "Scotland" },
  { value: "East Renfrewshire Council", label: "East Renfrewshire Council", group: "Scotland" },
  { value: "Edinburgh City Council", label: "Edinburgh City Council", group: "Scotland" },
  { value: "Falkirk Council", label: "Falkirk Council", group: "Scotland" },
  { value: "Fife Council", label: "Fife Council", group: "Scotland" },
  { value: "Glasgow City Council", label: "Glasgow City Council", group: "Scotland" },
  { value: "Highland Council", label: "Highland Council", group: "Scotland" },
  { value: "Inverclyde Council", label: "Inverclyde Council", group: "Scotland" },
  { value: "Midlothian Council", label: "Midlothian Council", group: "Scotland" },
  { value: "Moray Council", label: "Moray Council", group: "Scotland" },
  { value: "North Ayrshire Council", label: "North Ayrshire Council", group: "Scotland" },
  { value: "North Lanarkshire Council", label: "North Lanarkshire Council", group: "Scotland" },
  { value: "Orkney Islands Council", label: "Orkney Islands Council", group: "Scotland" },
  { value: "Perth and Kinross Council", label: "Perth and Kinross Council", group: "Scotland" },
  { value: "Renfrewshire Council", label: "Renfrewshire Council", group: "Scotland" },
  { value: "Scottish Borders Council", label: "Scottish Borders Council", group: "Scotland" },
  { value: "Shetland Islands Council", label: "Shetland Islands Council", group: "Scotland" },
  { value: "South Ayrshire Council", label: "South Ayrshire Council", group: "Scotland" },
  { value: "South Lanarkshire Council", label: "South Lanarkshire Council", group: "Scotland" },
  { value: "Stirling Council", label: "Stirling Council", group: "Scotland" },
  { value: "West Dunbartonshire Council", label: "West Dunbartonshire Council", group: "Scotland" },
  { value: "West Lothian Council", label: "West Lothian Council", group: "Scotland" },
  { value: "Comhairle nan Eilean Siar (Western Isles Council)", label: "Comhairle nan Eilean Siar (Western Isles Council)", group: "Scotland" },
  // Northern Ireland
  { value: "Antrim and Newtownabbey Borough Council", label: "Antrim and Newtownabbey Borough Council", group: "Northern Ireland" },
  { value: "Ards and North Down Borough Council", label: "Ards and North Down Borough Council", group: "Northern Ireland" },
  { value: "Armagh City Banbridge and Craigavon Borough Council", label: "Armagh City Banbridge and Craigavon Borough Council", group: "Northern Ireland" },
  { value: "Belfast City Council", label: "Belfast City Council", group: "Northern Ireland" },
  { value: "Causeway Coast and Glens Borough Council", label: "Causeway Coast and Glens Borough Council", group: "Northern Ireland" },
  { value: "Derry City and Strabane District Council", label: "Derry City and Strabane District Council", group: "Northern Ireland" },
  { value: "Fermanagh and Omagh District Council", label: "Fermanagh and Omagh District Council", group: "Northern Ireland" },
  { value: "Lisburn and Castlereagh City Council", label: "Lisburn and Castlereagh City Council", group: "Northern Ireland" },
  { value: "Mid and East Antrim Borough Council", label: "Mid and East Antrim Borough Council", group: "Northern Ireland" },
  { value: "Mid Ulster District Council", label: "Mid Ulster District Council", group: "Northern Ireland" },
  { value: "Newry Mourne and Down District Council", label: "Newry Mourne and Down District Council", group: "Northern Ireland" },
];

export const PROPERTY_TYPE_LABELS = {
  "18plus_accommodation": "18+ Accommodation",
  "24hours_housing": "24 Hours Housing",
  "care_services": "Care Services",
  "outreach": "Outreach",
  // legacy values
  "18_plus": "18+ Accommodation",
  "24_hours": "24 Hours Housing",
  "care": "Care Services",
};

export function fmtGBP(n) {
  return `£${(n || 0).toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function getMonthBounds(year, month) {
  const from = new Date(year, month, 1);
  const to = new Date(year, month + 1, 0);
  return {
    from: from.toISOString().split("T")[0],
    to: to.toISOString().split("T")[0],
    days: to.getDate(),
  };
}