package db

import (
	"log"

	"carecore-backend/models"

	"gorm.io/gorm"
)

// SeedMakerCheckerMatrix populates the org-wide maker/checker reference table
// from the approved governance matrix. Idempotent — skips rows that already
// exist for the org (matched by module_key).
//
// Accepts a *gorm.DB rather than using the global DB directly, so this can
// run either against the default connection at startup, or inside a
// tenant-scoped connection (app.current_org set) when provisioning a brand
// new organisation via CreateOrganisation.
func SeedMakerCheckerMatrix(tx *gorm.DB, orgID string) {
	log.Println("Seeding maker-checker matrix...")

	rows := []models.MakerCheckerMatrix{
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Residents",
			ModuleName:          "Resident/YP creation",
			ModuleKey:           "residents_resident_yp_creation",
			MakerRolesRaw:       "Admin Officer, Team Manager, RSM",
			CheckerRolesRaw:     "Team Manager / RSM",
			EscalationRolesRaw:  "RSM / Regional Manager for high-risk placement",
			MakerRoleSlugs:      models.StringArray{"admin_officer", "team_manager", "rsm"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "rsm"},
			EscalationRoleSlugs: models.StringArray{"rsm", "regional_manager"},
			LogicalFlow:         "Draft profile -> placement review -> active placement or returned/rejected. Approve home assignment, service type, key worker and risk category.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Residents",
			ModuleName:          "Support Plans",
			ModuleKey:           "residents_support_plans",
			MakerRolesRaw:       "SW contributes; TL/TM drafts",
			CheckerRolesRaw:     "Team Manager",
			EscalationRolesRaw:  "RSM; Risk Manager if risk-linked",
			MakerRoleSlugs:      models.StringArray{"team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm", "risk_manager"},
			LogicalFlow:         "Draft -> submitted -> TM review -> risk review if needed -> RSM sign-off -> active version. Version locked.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Residents",
			ModuleName:          "Placement Plan",
			ModuleKey:           "residents_placement_plan",
			MakerRolesRaw:       "TL/TM/RSM",
			CheckerRolesRaw:     "RSM",
			EscalationRolesRaw:  "RSM / Regional Manager",
			MakerRoleSlugs:      models.StringArray{"team_leader", "team_manager", "rsm"},
			CheckerRoleSlugs:    models.StringArray{"rsm"},
			EscalationRoleSlugs: models.StringArray{"rsm", "regional_manager"},
			LogicalFlow:         "Draft -> manager review -> approved active placement plan -> scheduled review.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Residents",
			ModuleName:          "ILS",
			ModuleKey:           "residents_ils",
			MakerRolesRaw:       "SW/TL",
			CheckerRolesRaw:     "TL",
			EscalationRolesRaw:  "TM for milestone completion",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_leader"},
			EscalationRoleSlugs: models.StringArray{"team_manager"},
			LogicalFlow:         "Progress recorded -> evidence submitted -> reviewed -> milestone confirmed or returned for more evidence.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Residents",
			ModuleName:          "Referrals",
			ModuleKey:           "residents_referrals",
			MakerRolesRaw:       "SW/TL/TM/external professional",
			CheckerRolesRaw:     "TM",
			EscalationRolesRaw:  "RSM if safeguarding/high-risk",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "team_manager", "external_professional"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Referral drafted -> submitted -> triaged -> accepted/rejected/escalated -> action assigned -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Safety",
			ModuleName:          "Risk Assessment",
			ModuleKey:           "safety_risk_assessment",
			MakerRolesRaw:       "TL/TM/Risk Manager",
			CheckerRolesRaw:     "Risk Manager",
			EscalationRolesRaw:  "RSM",
			MakerRoleSlugs:      models.StringArray{"team_leader", "team_manager", "risk_manager"},
			CheckerRoleSlugs:    models.StringArray{"risk_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Draft risk assessment -> risk review -> signed off -> active version. Old versions remain read-only. No Risk Officer stage.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Safety",
			ModuleName:          "Behaviour Management",
			ModuleKey:           "safety_behaviour_management",
			MakerRolesRaw:       "TL/TM/Risk Manager",
			CheckerRolesRaw:     "TM/Risk Manager",
			EscalationRolesRaw:  "RSM for high-risk/restraint-linked",
			MakerRoleSlugs:      models.StringArray{"team_leader", "team_manager", "risk_manager"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "risk_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Draft plan -> risk/management review -> signed off -> active plan. Escalate restraint/police/repeated aggression.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Safety",
			ModuleName:          "Incident Logs",
			ModuleKey:           "safety_incident_logs",
			MakerRolesRaw:       "SW/TL/TM",
			CheckerRolesRaw:     "TL low risk; TM medium/high",
			EscalationRolesRaw:  "RSM critical/Reg 27/Ofsted",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "team_manager"},
			CheckerRoleSlugs:    models.StringArray{},
			EscalationRoleSlugs: models.StringArray{},
			LogicalFlow:         "Logged -> submitted -> TL review -> TM review if needed -> RSM sign-off if serious -> external notification decision -> closed. Original narrative locked.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Safety",
			ModuleName:          "Missing Episode",
			ModuleKey:           "safety_missing_episode",
			MakerRolesRaw:       "SW/TL/TM",
			CheckerRolesRaw:     "TL initial review; TM full review",
			EscalationRolesRaw:  "RSM final closure",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "team_manager"},
			CheckerRoleSlugs:    models.StringArray{},
			EscalationRoleSlugs: models.StringArray{},
			LogicalFlow:         "Logged -> immediate alert -> initial review -> return/found update -> return interview -> risk/support plan update -> closure.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Safety",
			ModuleName:          "Exploitation Risk",
			ModuleKey:           "safety_exploitation_risk",
			MakerRolesRaw:       "SW raises concern; TL/TM/Risk Manager assesses",
			CheckerRolesRaw:     "Risk Manager",
			EscalationRolesRaw:  "RSM",
			MakerRoleSlugs:      models.StringArray{"team_leader", "team_manager"},
			CheckerRoleSlugs:    models.StringArray{"risk_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Concern raised -> risk review -> risk level assigned -> control plan signed off -> review date set.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Records",
			ModuleName:          "Daily Logs",
			ModuleKey:           "records_daily_logs",
			MakerRolesRaw:       "SW/TL",
			CheckerRolesRaw:     "TL only if flagged",
			EscalationRolesRaw:  "TM/RSM if escalated",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{},
			EscalationRoleSlugs: models.StringArray{"team_manager", "rsm"},
			LogicalFlow:         "Routine logs may auto-close. Flagged logs create review workflow if safeguarding/incident/missing/health/complaint/placement concern appears.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Records",
			ModuleName:          "Visit Reports",
			ModuleKey:           "records_visit_reports",
			MakerRolesRaw:       "SW/TL/external professional",
			CheckerRolesRaw:     "TL/TM",
			EscalationRolesRaw:  "RSM if serious",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "external_professional"},
			CheckerRoleSlugs:    models.StringArray{"team_leader", "team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Created -> submitted -> manager review -> accepted/returned/escalated.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Records",
			ModuleName:          "Complaints & Compliments",
			ModuleKey:           "records_complaints_compliments",
			MakerRolesRaw:       "YP, external, SW, Admin, TL",
			CheckerRolesRaw:     "TM/RSM",
			EscalationRolesRaw:  "RSM/Regional Manager serious complaint; Compliance Manager for QA",
			MakerRoleSlugs:      models.StringArray{"resident", "external_professional", "support_worker", "admin_officer", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "rsm"},
			EscalationRoleSlugs: models.StringArray{"rsm", "compliance_manager"},
			LogicalFlow:         "Received -> acknowledged -> investigation assigned -> outcome proposed -> sign-off -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Records",
			ModuleName:          "Legal/Restrictions/Warnings",
			ModuleKey:           "records_legal_restrictions_warnings",
			MakerRolesRaw:       "TL/TM/RSM",
			CheckerRolesRaw:     "RSM",
			EscalationRolesRaw:  "Regional Manager for serious restrictions",
			MakerRoleSlugs:      models.StringArray{"team_leader", "team_manager", "rsm"},
			CheckerRoleSlugs:    models.StringArray{"rsm"},
			EscalationRoleSlugs: models.StringArray{"regional_manager"},
			LogicalFlow:         "Draft -> review -> approved/returned -> issued -> acknowledged -> active/closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Records",
			ModuleName:          "YP Voice/Feedback",
			ModuleKey:           "records_yp_voice_feedback",
			MakerRolesRaw:       "YP, SW, TL, Compliance role",
			CheckerRolesRaw:     "TM/Compliance Manager",
			EscalationRolesRaw:  "RSM if serious",
			MakerRoleSlugs:      models.StringArray{"resident", "support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "compliance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Submitted -> reviewed -> action required/no action -> owner assigned -> closed. Do not use \"approved\".",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Wellbeing",
			ModuleName:          "Health",
			ModuleKey:           "wellbeing_health",
			MakerRolesRaw:       "SW/TL",
			CheckerRolesRaw:     "TL",
			EscalationRolesRaw:  "TM/RSM if concern",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_leader"},
			EscalationRoleSlugs: models.StringArray{"team_manager", "rsm"},
			LogicalFlow:         "Health update -> routine closure or submitted if concern -> follow-up assigned -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Wellbeing",
			ModuleName:          "Therapeutic Plan",
			ModuleKey:           "wellbeing_therapeutic_plan",
			MakerRolesRaw:       "TM/external professional/RSM",
			CheckerRolesRaw:     "RSM",
			EscalationRolesRaw:  "Risk Manager/RSM if risk-linked",
			MakerRoleSlugs:      models.StringArray{"team_manager", "external_professional", "rsm"},
			CheckerRoleSlugs:    models.StringArray{"rsm"},
			EscalationRoleSlugs: models.StringArray{"risk_manager", "rsm"},
			LogicalFlow:         "Draft -> professional/manager review -> signed off -> active plan.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Life & Community",
			ModuleName:          "Appointments",
			ModuleKey:           "life_community_appointments",
			MakerRolesRaw:       "SW/TL/Admin Officer",
			CheckerRolesRaw:     "TL routine; TM if missed/concerning",
			EscalationRolesRaw:  "RSM if repeated issue",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "admin_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Scheduled -> outcome recorded -> routine close or review if missed/concern -> action.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Education/Employment/NEET",
			ModuleName:          "Education/Employment/NEET",
			ModuleKey:           "education_employment_neet",
			MakerRolesRaw:       "SW/TL/TM",
			CheckerRolesRaw:     "TL/TM",
			EscalationRolesRaw:  "RSM if statutory/placement concern",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "team_manager"},
			CheckerRoleSlugs:    models.StringArray{"team_leader", "team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Record created -> concern/progress submitted -> reviewed -> action plan or active monitoring.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Family Contact",
			ModuleName:          "Family Contact",
			ModuleKey:           "family_contact",
			MakerRolesRaw:       "SW/TL",
			CheckerRolesRaw:     "TL/TM",
			EscalationRolesRaw:  "RSM if restricted/high-risk contact",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_leader", "team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Contact record -> submitted if risk/concern -> reviewed -> actioned/closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "18+",
			ModuleName:          "Pathway Plans",
			ModuleKey:           "18_pathway_plans",
			MakerRolesRaw:       "TL/TM/PA/key worker",
			CheckerRolesRaw:     "TM",
			EscalationRolesRaw:  "RSM",
			MakerRoleSlugs:      models.StringArray{"team_leader", "team_manager", "personal_adviser", "support_worker"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Draft -> submitted -> manager review -> signed off -> active plan.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "18+",
			ModuleName:          "Move-On Planning",
			ModuleKey:           "18_move_on_planning",
			MakerRolesRaw:       "SW/TL/TM",
			CheckerRolesRaw:     "TM",
			EscalationRolesRaw:  "RSM",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "team_manager"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Draft -> manager review -> approved move-on pathway -> actions tracked -> closed on move-on.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "18+",
			ModuleName:          "PA Management",
			ModuleKey:           "18_pa_management",
			MakerRolesRaw:       "PA/SW/TL",
			CheckerRolesRaw:     "TM",
			EscalationRolesRaw:  "RSM if concern",
			MakerRoleSlugs:      models.StringArray{"personal_adviser", "support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "PA visit/action logged -> submitted -> reviewed -> actioned/closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "18+",
			ModuleName:          "Benefits & Finance",
			ModuleKey:           "18_benefits_finance",
			MakerRolesRaw:       "SW/TL/Finance Officer",
			CheckerRolesRaw:     "TM and Finance Manager if money movement",
			EscalationRolesRaw:  "RSM if high-risk safeguarding/financial exploitation issue",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "finance_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "finance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Entry created -> manager/finance review -> approved/actioned/reconciled.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "24h",
			ModuleName:          "Rota/Shifts",
			ModuleKey:           "24h_rota_shifts",
			MakerRolesRaw:       "TL/TM/Admin",
			CheckerRolesRaw:     "TM",
			EscalationRolesRaw:  "HR Manager if staffing compliance issue",
			MakerRoleSlugs:      models.StringArray{"team_leader", "team_manager", "admin_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"hr_manager"},
			LogicalFlow:         "Rota drafted -> manager review -> published.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "24h",
			ModuleName:          "Shift Handover",
			ModuleKey:           "24h_shift_handover",
			MakerRolesRaw:       "Outgoing SW/TL",
			CheckerRolesRaw:     "Incoming staff acknowledgement; TL review",
			EscalationRolesRaw:  "TM/RSM if risk-triggered",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{},
			EscalationRoleSlugs: models.StringArray{"team_manager", "rsm"},
			LogicalFlow:         "Submitted -> acknowledged -> reviewed if risk trigger -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "24h",
			ModuleName:          "Visitor Log",
			ModuleKey:           "24h_visitor_log",
			MakerRolesRaw:       "SW/reception/admin/visitor",
			CheckerRolesRaw:     "TL if flagged",
			EscalationRolesRaw:  "RSM if concern",
			MakerRoleSlugs:      models.StringArray{"support_worker", "admin_officer", "external_professional"},
			CheckerRoleSlugs:    models.StringArray{"team_leader"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Routine auto-close or flagged review.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "Onboarding",
			ModuleKey:           "staff_hr_onboarding",
			MakerRolesRaw:       "HR Officer/Admin/TM",
			CheckerRolesRaw:     "HR Manager and Compliance Manager",
			EscalationRolesRaw:  "RSM for home/role activation where required",
			MakerRoleSlugs:      models.StringArray{"hr_officer", "admin_officer", "team_manager"},
			CheckerRoleSlugs:    models.StringArray{"hr_manager", "compliance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Draft profile -> docs uploaded -> HR review -> compliance evidence review -> manager approval -> active staff.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "Staff Movement",
			ModuleKey:           "staff_hr_staff_movement",
			MakerRolesRaw:       "HR Officer/Admin/TM",
			CheckerRolesRaw:     "HR Manager/RSM",
			EscalationRolesRaw:  "Regional Manager for senior roles",
			MakerRoleSlugs:      models.StringArray{"hr_officer", "admin_officer", "team_manager"},
			CheckerRoleSlugs:    models.StringArray{"hr_manager", "rsm"},
			EscalationRoleSlugs: models.StringArray{"regional_manager"},
			LogicalFlow:         "Movement drafted -> HR review -> operational manager review -> approved -> effective date applied.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "Leave",
			ModuleKey:           "staff_hr_leave",
			MakerRolesRaw:       "Staff member",
			CheckerRolesRaw:     "Line Manager/TL/TM",
			EscalationRolesRaw:  "HR Manager for exceptions",
			MakerRoleSlugs:      models.StringArray{"support_worker"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "team_leader"},
			EscalationRoleSlugs: models.StringArray{"hr_manager"},
			LogicalFlow:         "Leave requested -> manager review -> approved/rejected -> HR record updated.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "TOIL",
			ModuleKey:           "staff_hr_toil",
			MakerRolesRaw:       "Staff/TL",
			CheckerRolesRaw:     "TM",
			EscalationRolesRaw:  "HR Manager",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"hr_manager"},
			LogicalFlow:         "Claimed -> manager review -> approved/rejected.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "Timesheets/Salary",
			ModuleKey:           "staff_hr_timesheets_salary",
			MakerRolesRaw:       "Staff/TL/HR Officer",
			CheckerRolesRaw:     "TM/HR Manager",
			EscalationRolesRaw:  "Finance Manager payment readiness",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "hr_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "hr_manager"},
			EscalationRoleSlugs: models.StringArray{},
			LogicalFlow:         "Submitted -> line manager review -> HR review -> finance approval -> payroll ready.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "Expenses",
			ModuleKey:           "staff_hr_expenses",
			MakerRolesRaw:       "Staff/Admin/Finance Officer",
			CheckerRolesRaw:     "Line Manager",
			EscalationRolesRaw:  "Finance Manager",
			MakerRoleSlugs:      models.StringArray{"support_worker", "admin_officer", "finance_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_manager"},
			EscalationRoleSlugs: models.StringArray{"finance_manager"},
			LogicalFlow:         "Submitted -> line manager review -> finance review -> approved for payment -> reimbursed. Claimant cannot approve.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "Training",
			ModuleKey:           "staff_hr_training",
			MakerRolesRaw:       "Staff completion; HR uploads evidence",
			CheckerRolesRaw:     "HR Manager",
			EscalationRolesRaw:  "Compliance Manager/RSM for mandatory compliance gaps",
			MakerRoleSlugs:      models.StringArray{},
			CheckerRoleSlugs:    models.StringArray{"hr_manager"},
			EscalationRoleSlugs: models.StringArray{"compliance_manager", "rsm"},
			LogicalFlow:         "Assigned -> completed -> evidence submitted -> verified -> matrix updated.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "Supervision",
			ModuleKey:           "staff_hr_supervision",
			MakerRolesRaw:       "TL/TM/HR Officer",
			CheckerRolesRaw:     "TM/HR Manager",
			EscalationRolesRaw:  "RSM if escalated",
			MakerRoleSlugs:      models.StringArray{"team_leader", "team_manager", "hr_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "hr_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Draft -> staff acknowledgement -> manager sign-off -> HR compliance updated.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Staff & HR",
			ModuleName:          "Disciplinary",
			ModuleKey:           "staff_hr_disciplinary",
			MakerRolesRaw:       "HR/TM/RSM",
			CheckerRolesRaw:     "HR Manager",
			EscalationRolesRaw:  "RSM/Regional Manager serious cases",
			MakerRoleSlugs:      models.StringArray{"team_manager", "rsm"},
			CheckerRoleSlugs:    models.StringArray{"hr_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Case opened -> investigation assigned -> evidence reviewed -> outcome proposed -> senior sign-off -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Finance",
			ModuleName:          "Placement Fees",
			ModuleKey:           "finance_placement_fees",
			MakerRolesRaw:       "Finance Officer/Admin/RSM",
			CheckerRolesRaw:     "Finance Manager",
			EscalationRolesRaw:  "RSM if placement data dispute",
			MakerRoleSlugs:      models.StringArray{"finance_officer", "admin_officer", "rsm"},
			CheckerRoleSlugs:    models.StringArray{"finance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Draft fee -> finance review -> active approved fee.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Finance",
			ModuleName:          "Invoicing",
			ModuleKey:           "finance_invoicing",
			MakerRolesRaw:       "Finance Officer/Admin",
			CheckerRolesRaw:     "Finance Manager",
			EscalationRolesRaw:  "N/A unless disputed",
			MakerRoleSlugs:      models.StringArray{"finance_officer", "admin_officer"},
			CheckerRoleSlugs:    models.StringArray{"finance_manager"},
			EscalationRoleSlugs: models.StringArray{},
			LogicalFlow:         "Draft invoice -> finance review -> approved -> issued -> paid/part paid/overdue.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Finance",
			ModuleName:          "Petty Cash",
			ModuleKey:           "finance_petty_cash",
			MakerRolesRaw:       "SW/TL/Admin/Finance Officer",
			CheckerRolesRaw:     "TL/TM for operational confirmation",
			EscalationRolesRaw:  "Finance Manager final; delegated finance approver if Finance Manager absent; RSM for exception/high-risk use.",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "admin_officer", "finance_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_leader", "team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Request/spend logged -> manager review -> finance approval -> reconciled.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Finance",
			ModuleName:          "Allowances & Savings",
			ModuleKey:           "finance_allowances_savings",
			MakerRolesRaw:       "SW/TL/Finance Officer",
			CheckerRolesRaw:     "TM and Finance Manager",
			EscalationRolesRaw:  "RSM if financial safeguarding concern",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "finance_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_manager", "finance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Entry -> manager review -> finance review -> approved/reconciled.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Finance",
			ModuleName:          "Bills & Expenses",
			ModuleKey:           "finance_bills_expenses",
			MakerRolesRaw:       "Finance Officer/Admin; SW/TL can submit home bill/receipt or utility evidence from front line",
			CheckerRolesRaw:     "If submitted by SW: TL or TM first validates operational/home context; then Admin Manager or delegated equivalent checks document/vendor/category; Finance Manager approves payment/posting where financial authorisation is required.",
			EscalationRolesRaw:  "If TL/TM/Admin Manager/Finance Manager is on leave, route to active delegate/equivalent approver; RSM/Regional Manager for high-value or unresolved exceptions.",
			MakerRoleSlugs:      models.StringArray{"finance_officer", "admin_officer", "support_worker"},
			CheckerRoleSlugs:    models.StringArray{},
			EscalationRoleSlugs: models.StringArray{"team_manager", "admin_manager", "rsm", "regional_manager"},
			LogicalFlow:         "SW bill submitted -> TL/TM validation -> Admin Manager/equivalent admin checker -> Finance Manager payment approval if payable -> posted -> paid/reconciled. Finance/Admin-submitted bills skip SW validation but still require maker-checker and absence fallback.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Finance",
			ModuleName:          "Budgets",
			ModuleKey:           "finance_budgets",
			MakerRolesRaw:       "Finance Officer/Finance Manager/Admin Manager",
			CheckerRolesRaw:     "Finance Manager",
			EscalationRolesRaw:  "RSM/Regional Manager major changes",
			MakerRoleSlugs:      models.StringArray{"finance_officer", "finance_manager", "admin_manager"},
			CheckerRoleSlugs:    models.StringArray{"finance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Draft budget -> review -> senior approval if required -> active.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Homes",
			ModuleName:          "Home Creation/Details",
			ModuleKey:           "homes_home_creation_details",
			MakerRolesRaw:       "Admin Officer/Admin Manager",
			CheckerRolesRaw:     "Admin Manager",
			EscalationRolesRaw:  "RSM/Regional Manager",
			MakerRoleSlugs:      models.StringArray{"admin_officer", "admin_manager"},
			CheckerRoleSlugs:    models.StringArray{"admin_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm", "regional_manager"},
			LogicalFlow:         "Draft home -> documents added -> admin review -> senior approval -> active home.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Homes",
			ModuleName:          "Property/Tenancy/Documents",
			ModuleKey:           "homes_property_tenancy_documents",
			MakerRolesRaw:       "Admin Officer/Admin Manager",
			CheckerRolesRaw:     "Admin Manager",
			EscalationRolesRaw:  "Compliance/Finance Manager depending document",
			MakerRoleSlugs:      models.StringArray{"admin_officer", "admin_manager"},
			CheckerRoleSlugs:    models.StringArray{"admin_manager"},
			EscalationRoleSlugs: models.StringArray{},
			LogicalFlow:         "Document/change submitted -> review -> approved/returned.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Homes",
			ModuleName:          "Checks/Chores/Audits",
			ModuleKey:           "homes_checks_chores_audits",
			MakerRolesRaw:       "SW/TL/Maintenance Officer",
			CheckerRolesRaw:     "TL/Admin Manager",
			EscalationRolesRaw:  "RSM for failed safety check; delegated TL/TM/Admin Manager where primary reviewer is absent.",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "maintenance_officer"},
			CheckerRoleSlugs:    models.StringArray{"team_leader", "admin_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm", "team_leader", "team_manager", "admin_manager"},
			LogicalFlow:         "Check completed -> auto-close if pass; failed item creates review and maintenance/risk/compliance action.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Homes/Maintenance",
			ModuleName:          "Maintenance Logs",
			ModuleKey:           "homes_maintenance_maintenance_logs",
			MakerRolesRaw:       "SW/TL/Admin/Maintenance",
			CheckerRolesRaw:     "Admin Manager",
			EscalationRolesRaw:  "Finance Manager cost; RSM safety-critical; delegated admin/finance equivalent where primary manager is absent.",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader", "admin_officer"},
			CheckerRoleSlugs:    models.StringArray{"admin_manager"},
			EscalationRoleSlugs: models.StringArray{"admin_officer"},
			LogicalFlow:         "Issue -> validation -> assignment -> quote if needed -> cost approval -> completion verification -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Homes",
			ModuleName:          "Assets",
			ModuleKey:           "homes_assets",
			MakerRolesRaw:       "Admin/Maintenance/Finance",
			CheckerRolesRaw:     "Admin Manager",
			EscalationRolesRaw:  "Finance Manager high value",
			MakerRoleSlugs:      models.StringArray{"admin_officer"},
			CheckerRoleSlugs:    models.StringArray{"admin_manager"},
			EscalationRoleSlugs: models.StringArray{},
			LogicalFlow:         "Asset created -> verified -> active asset; disposal request -> disposal approved -> archived.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Homes",
			ModuleName:          "Accidents/Illness",
			ModuleKey:           "homes_accidents_illness",
			MakerRolesRaw:       "SW/TL",
			CheckerRolesRaw:     "TL/TM",
			EscalationRolesRaw:  "RSM if serious",
			MakerRoleSlugs:      models.StringArray{"support_worker", "team_leader"},
			CheckerRoleSlugs:    models.StringArray{"team_leader", "team_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Logged -> submitted -> manager review -> action required -> signed off -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Compliance",
			ModuleName:          "Reg 32 Report",
			ModuleKey:           "compliance_reg_32_report",
			MakerRolesRaw:       "Compliance Manager/RSM/TM",
			CheckerRolesRaw:     "Compliance Manager/RSM",
			EscalationRolesRaw:  "RSM / Regional Manager",
			MakerRoleSlugs:      models.StringArray{"compliance_manager", "rsm", "team_manager"},
			CheckerRoleSlugs:    models.StringArray{"compliance_manager", "rsm"},
			EscalationRoleSlugs: models.StringArray{"rsm", "regional_manager"},
			LogicalFlow:         "Draft -> evidence pulled -> notes added -> submitted -> review -> sign-off -> locked final report.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Compliance",
			ModuleName:          "Internal Audit",
			ModuleKey:           "compliance_internal_audit",
			MakerRolesRaw:       "Compliance Manager/RSM",
			CheckerRolesRaw:     "Compliance Manager",
			EscalationRolesRaw:  "RSM/Regional Manager",
			MakerRoleSlugs:      models.StringArray{"compliance_manager", "rsm"},
			CheckerRoleSlugs:    models.StringArray{"compliance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm", "regional_manager"},
			LogicalFlow:         "Audit started -> findings -> actions assigned -> submitted -> review -> closed when evidence complete.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Compliance",
			ModuleName:          "Quality Assurance",
			ModuleKey:           "compliance_quality_assurance",
			MakerRolesRaw:       "Compliance Manager/RSM",
			CheckerRolesRaw:     "Compliance Manager",
			EscalationRolesRaw:  "RSM",
			MakerRoleSlugs:      models.StringArray{"compliance_manager", "rsm"},
			CheckerRoleSlugs:    models.StringArray{"compliance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "QA review -> findings -> actions -> owners complete -> reviewer verifies -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Compliance",
			ModuleName:          "Ofsted Notifications",
			ModuleKey:           "compliance_ofsted_notifications",
			MakerRolesRaw:       "TM/RSM/Compliance Manager",
			CheckerRolesRaw:     "RSM/Compliance Manager",
			EscalationRolesRaw:  "RSM / Regional Manager for critical",
			MakerRoleSlugs:      models.StringArray{"team_manager", "rsm", "compliance_manager"},
			CheckerRoleSlugs:    models.StringArray{"rsm", "compliance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm", "regional_manager"},
			LogicalFlow:         "Drafted -> reviewed -> approved to submit -> submitted -> evidence stored -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Compliance",
			ModuleName:          "Reg 27/34 Actions",
			ModuleKey:           "compliance_reg_27_34_actions",
			MakerRolesRaw:       "TM/RSM/Compliance Manager",
			CheckerRolesRaw:     "Compliance Manager/RSM",
			EscalationRolesRaw:  "RSM/Regional Manager",
			MakerRoleSlugs:      models.StringArray{"team_manager", "rsm", "compliance_manager"},
			CheckerRoleSlugs:    models.StringArray{"compliance_manager", "rsm"},
			EscalationRoleSlugs: models.StringArray{"rsm", "regional_manager"},
			LogicalFlow:         "Action/notification created -> owner assigned -> evidence uploaded -> reviewer checks -> closed.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Tenant Admin",
			ModuleName:          "Role/Permission Changes",
			ModuleKey:           "tenant_admin_role_permission_changes",
			MakerRolesRaw:       "Tenant Admin/Admin Manager/HR Manager",
			CheckerRolesRaw:     "RSM/Regional Manager",
			EscalationRolesRaw:  "Super Admin if platform-level",
			MakerRoleSlugs:      models.StringArray{"tenant_admin", "admin_manager", "hr_manager"},
			CheckerRoleSlugs:    models.StringArray{"rsm", "regional_manager"},
			EscalationRoleSlugs: models.StringArray{"super_admin"},
			LogicalFlow:         "Change requested -> senior review -> approved -> permission updated -> audit logged.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
		{
			Base:                models.Base{OrgID: orgID, CreatedBy: "system"},
			Category:            "Tenant Admin",
			ModuleName:          "External Agency Access",
			ModuleKey:           "tenant_admin_external_agency_access",
			MakerRolesRaw:       "Admin Officer/Admin Manager/Tenant Admin",
			CheckerRolesRaw:     "Admin Manager/Compliance Manager",
			EscalationRolesRaw:  "RSM if sensitive safeguarding/external access",
			MakerRoleSlugs:      models.StringArray{"admin_officer", "admin_manager", "tenant_admin"},
			CheckerRoleSlugs:    models.StringArray{"admin_manager", "compliance_manager"},
			EscalationRoleSlugs: models.StringArray{"rsm"},
			LogicalFlow:         "Agency created -> scope defined -> reviewed -> approved -> portal access enabled.",
			AllowSelfApproval:   false,
			IsActive:            true,
		},
	}

	seededCount := 0
	for _, row := range rows {
		var existing models.MakerCheckerMatrix
		err := tx.Where("org_id = ? AND module_key = ?", orgID, row.ModuleKey).First(&existing).Error
		if err == nil {
			continue // already seeded
		}
		if err := tx.Create(&row).Error; err != nil {
			log.Printf("Failed to seed maker-checker row %q: %v", row.ModuleKey, err)
			continue
		}
		seededCount++
	}

	log.Printf("Maker-checker matrix seeded: %d new rows (of %d total)", seededCount, len(rows))
}