import { X, Printer, Download, Shield, Check } from "lucide-react";
import { format } from "date-fns";
import { base44 } from "@/api/base44Client";
import { toast } from "sonner";

export default function Reg32ReportModal({
  open, onClose,
  orgName, reviewerName, reviewerOrg, completedDate,
  periodStart, periodEnd,
  strengthsNarrative, improvementsNarrative, actionPlanNarrative,
  selectedYPs, residents, homes,
  reportId, status, ypViewsMethod, ypViewsCount, ypViewsSummary, ypViewsActions,
  incidents = [], mfhRecords = [], complaints = [], trainingRecords = [], supervisionRecords = [],
}) {
  if (!open) return null;

  const handlePrint = () => window.print();

  const handleExportHTML = () => {
    const today = format(new Date(), "dd MMMM yyyy");
    const fmtDate = (d) => { try { return d ? format(new Date(d), "dd MMMM yyyy") : "—"; } catch { return d || "—"; } };
    
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Regulation 32 Report</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; color: #333; }
    h1 { font-size: 24px; margin-bottom: 10px; }
    h2 { font-size: 18px; margin-top: 30px; margin-bottom: 15px; border-bottom: 2px solid #333; padding-bottom: 8px; }
    p { margin: 10px 0; }
    footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; text-align: center; }
    .report-meta { background: #f5f5f5; padding: 15px; margin-bottom: 30px; border-radius: 5px; }
    .report-meta p { margin: 5px 0; }
  </style>
</head>
<body>

<h1>Regulation 32 — Quality of Support Review</h1>
<h2>${orgName || 'Evolvix Digital Ltd'}</h2>

<div class="report-meta">
  <p><strong>Review period:</strong> ${fmtDate(periodStart)} to ${fmtDate(periodEnd)}</p>
  <p><strong>Independent reviewer:</strong> ${reviewerName || '—'}, ${reviewerOrg || '—'}</p>
  <p><strong>Date completed:</strong> ${fmtDate(completedDate)}</p>
  <p><strong>Status:</strong> ${status || 'Draft'}</p>
</div>

<h2>Young People's Views</h2>
<p><strong>Method of engagement:</strong> ${ypViewsMethod || '—'}</p>
<p><strong>Number of young people consulted:</strong> ${ypViewsCount || '—'}</p>
<p><strong>Summary of views:</strong></p>
<p>${ypViewsSummary || '—'}</p>
<p><strong>Actions taken:</strong></p>
<p>${ypViewsActions || '—'}</p>

<h2>Strengths &amp; Quality of Support</h2>
<p>${strengthsNarrative || 'No narrative generated yet.'}</p>

<h2>Areas for Improvement</h2>
<p>${improvementsNarrative || 'No narrative generated yet.'}</p>

<h2>Action Plan — Next 6 Months</h2>
<p>${actionPlanNarrative || 'No action plan generated yet.'}</p>

<h2>Supporting Evidence</h2>
<p>This report is based on data from CareCore AI covering ${fmtDate(periodStart)} to ${fmtDate(periodEnd)}.</p>
<p>Incidents reviewed: ${incidents.length}. Missing episodes: ${mfhRecords.length}. Complaints: ${complaints.length}. Training compliance: ${trainingRecords.length} staff. Supervision records: ${supervisionRecords.length}.</p>

<footer>
Generated by CareCore AI on ${today}. Confidential — for Ofsted inspection use only.
</footer>

</body>
</html>`;

    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  };

  const handleMarkSubmitted = async () => {
    if (!reportId) {
      toast.error('Report ID not found');
      return;
    }
    try {
      await base44.entities.Reg32Report.update(reportId, {
        status: 'submitted',
        submitted_to_ofsted_date: format(new Date(), 'yyyy-MM-dd'),
      });
      toast.success('Report marked as submitted to Ofsted');
      onClose();
    } catch (e) {
      toast.error(`Error: ${e.message}`);
    }
  };

  const ypNames = (selectedYPs || [])
    .map(id => {
      const r = (residents || []).find(r => r.id === id);
      return r?.display_name || r?.initials || null;
    })
    .filter(Boolean);

  const homeNames = (homes || []).map(h => h.name).join(", ");
  const today = format(new Date(), "dd MMMM yyyy");
  const fmtDate = (d) => { try { return d ? format(new Date(d), "dd MMMM yyyy") : "—"; } catch { return d || "—"; } };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
      {/* Modal container */}
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[92vh] flex flex-col overflow-hidden">

        {/* Modal toolbar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-slate-50 shrink-0">
          <div className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-purple-600" />
            <span className="font-semibold text-slate-800">Regulation 32 — Quality of Support Review</span>
            <span className="ml-2 text-xs bg-purple-100 text-purple-700 font-semibold px-2 py-0.5 rounded-full">Preview</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleExportHTML}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium"
            >
              <Download className="w-4 h-4" /> Export HTML
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-white text-sm font-medium"
            >
              <Printer className="w-4 h-4" /> Print / PDF
            </button>
            {status !== 'submitted' && (
              <button
                onClick={handleMarkSubmitted}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-green-600 hover:bg-green-700 text-white text-sm font-medium"
              >
                <Check className="w-4 h-4" /> Mark as Submitted
              </button>
            )}
            <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-slate-200 text-slate-500">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Scrollable report body */}
        <div id="reg32-report-body" className="overflow-y-auto flex-1 px-10 py-8 bg-white text-slate-800 print:px-0 print:py-0">

          {/* Header */}
          <div className="border-b-2 border-slate-800 pb-5 mb-7">
            <div className="flex items-start justify-between">
              <div>
                <p className="text-xs font-semibold uppercase tracking-widest text-purple-600 mb-1">Regulation 32 — Children's Homes (England) Regulations 2015</p>
                <h1 className="text-2xl font-bold text-slate-900 leading-tight">Quality of Care Review</h1>
                <h2 className="text-base font-medium text-slate-600 mt-0.5">Independent Person's Report</h2>
              </div>
              <div className="text-right">
                <p className="text-sm font-bold text-slate-900">{orgName || "Evolvix Digital Ltd"}</p>
                <p className="text-xs text-slate-500 mt-0.5">Registered Children's Home Provider</p>
              </div>
            </div>
          </div>

          {/* Cover details table */}
          <div className="grid grid-cols-2 gap-x-8 gap-y-3 mb-8 text-sm">
            {[
              ["Review Period", `${fmtDate(periodStart)} – ${fmtDate(periodEnd)}`],
              ["Date Completed", fmtDate(completedDate)],
              ["Independent Reviewer", reviewerName || "—"],
              ["Reviewer Organisation", reviewerOrg || "—"],
              ["Homes Reviewed", homeNames || "—"],
              ["Report Reference", `REG32-${format(new Date(), "yyyy")}-${String(Math.floor(Math.random() * 900) + 100)}`],
            ].map(([label, value]) => (
              <div key={label} className="flex flex-col">
                <span className="text-[10px] font-semibold uppercase tracking-widest text-slate-400">{label}</span>
                <span className="font-medium text-slate-800 mt-0.5">{value}</span>
              </div>
            ))}
          </div>

          {/* YP section */}
          {ypNames.length > 0 && (
            <div className="mb-8 bg-slate-50 border border-slate-200 rounded-xl px-5 py-4">
              <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400 mb-2">Young People Involved in This Review</p>
              <div className="flex flex-wrap gap-2">
                {ypNames.map((n, i) => (
                  <span key={i} className="text-xs font-medium bg-purple-100 text-purple-700 px-2.5 py-1 rounded-full">{n}</span>
                ))}
              </div>
            </div>
          )}

          {/* Section 1 */}
          <Section
            number="1"
            title="Strengths and Quality of Support"
            regulation="Reg 32(2)(a)"
            content={strengthsNarrative}
            placeholder="No narrative generated yet. Use the AI generator to populate this section."
          />

          {/* Section 2 */}
          <Section
            number="2"
            title="Areas for Improvement"
            regulation="Reg 32(2)(b)"
            content={improvementsNarrative}
            placeholder="No narrative generated yet."
          />

          {/* Section 3 */}
          <Section
            number="3"
            title="Action Plan — Next 6 Months"
            regulation="Reg 32(2)(c)"
            content={actionPlanNarrative}
            placeholder="No action plan generated yet."
          />

          {/* Signature block */}
          <div className="mt-10 border-t border-slate-200 pt-8 grid grid-cols-2 gap-8">
            <div>
              <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Independent Reviewer</p>
              <div className="border-b border-slate-300 pb-1 mb-2 h-10" />
              <p className="text-sm font-medium">{reviewerName || "___________________________"}</p>
              <p className="text-xs text-slate-500">{reviewerOrg || "Organisation"}</p>
              <p className="text-xs text-slate-400 mt-2">Date: {fmtDate(completedDate)}</p>
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Responsible Individual / Registered Manager</p>
              <div className="border-b border-slate-300 pb-1 mb-2 h-10" />
              <p className="text-sm font-medium">___________________________</p>
              <p className="text-xs text-slate-500">{orgName || "Evolvix Digital Ltd"}</p>
              <p className="text-xs text-slate-400 mt-2">Date: _______________</p>
            </div>
          </div>

          {/* Footer note */}
          <div className="mt-8 text-center text-xs text-slate-400 border-t border-slate-100 pt-4">
            This report has been produced in accordance with Regulation 32 of the Children's Homes (England) Regulations 2015. 
            It must be submitted to Ofsted within 28 days of the review being completed and is not for public distribution.
            <br />
            <span className="font-medium">{orgName || "Evolvix Digital Ltd"}</span> · Report generated {today}
          </div>
        </div>
      </div>

      {/* Print styles injected inline */}
      <style>{`
        @media print {
          body > *:not(#reg32-print-root) { display: none !important; }
          #reg32-report-body { max-height: none !important; overflow: visible !important; }
        }
      `}</style>
    </div>
  );
}

function Section({ number, title, regulation, content, placeholder }) {
  return (
    <div className="mb-8">
      <div className="flex items-baseline gap-3 mb-3">
        <div className="w-7 h-7 rounded-full bg-purple-600 text-white flex items-center justify-center text-xs font-bold shrink-0">{number}</div>
        <div>
          <h3 className="font-bold text-slate-900 text-base">{title}</h3>
          <span className="text-[10px] font-semibold text-purple-500 uppercase tracking-wider">{regulation}</span>
        </div>
      </div>
      <div className="ml-10 bg-slate-50 border border-slate-200 rounded-xl px-5 py-4 text-sm text-slate-700 leading-relaxed whitespace-pre-wrap min-h-[80px]">
        {content || <span className="text-slate-400 italic">{placeholder}</span>}
      </div>
    </div>
  );
}