import { jsPDF } from "jspdf";
import { format } from "date-fns";
import { calcTrainingStatus } from "@/components/staff/training/TrainingStatusBadge";

const STATUS_SHORT = {
  completed: "Comp",
  valid: "Valid",
  expiring_soon: "Due",
  expired: "Overdue",
  not_started: "Not Start",
  in_progress: "In Prog",
  na: "N/A",
};

const STATUS_FILL = {
  completed: [220, 252, 231],
  valid: [220, 252, 231],
  expiring_soon: [254, 215, 170],
  expired: [254, 202, 202],
  not_started: [219, 234, 254],
  in_progress: [219, 234, 254],
  na: [241, 245, 249],
};

const STATUS_TEXT = {
  completed: [22, 101, 52],
  valid: [22, 101, 52],
  expiring_soon: [161, 98, 7],
  expired: [185, 28, 28],
  not_started: [30, 64, 175],
  in_progress: [30, 64, 175],
  na: [100, 116, 139],
};

export function generateTrainingMatrixReport({
  staff,
  courses,
  recordMap,
  stats,
  filters = {},
  generatedBy,
}) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a3" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;
  const usableW = pageW - margin * 2;

  const generatedAt = new Date();
  const dateStr = format(generatedAt, "d MMMM yyyy 'at' HH:mm");

  // ── Helper: draw header on each page ──
  const drawHeader = (pageNum, totalPages) => {
    // Top bar
    doc.setFillColor(30, 64, 175);
    doc.rect(0, 0, pageW, 24, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Training Matrix Compliance Report", margin, 11);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated: ${dateStr}`, margin, 17);
    doc.text(`Generated by: ${generatedBy?.name || "System"}`, margin, 21);
    if (totalPages > 1) {
      doc.text(`Page ${pageNum} of ${totalPages}`, pageW - margin - 40, 21, { align: "right" });
    }
  };

  // ── Metadata & Summary section (page 1 only) ──
  let y = 30;

  // Filters box
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, usableW, 24, 2, 2, "FD");
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Report Scope", margin + 4, y + 6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  const filterLines = [
    `Home: ${filters.home || "All Homes"}`,
    `Department: ${filters.department || "All Departments"}`,
    `Role: ${filters.role || "All Roles"}`,
    `Search: ${filters.search || "—"}${filters.search ? ` ("${filters.search}")` : ""}`,
  ];
  filterLines.forEach((line, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    doc.text(line, margin + 4 + col * (usableW / 2 - 4), y + 12 + row * 5);
  });
  y += 28;

  // Summary stats
  const statCards = [
    { label: "Total Staff", value: staff.length, color: [59, 130, 246] },
    { label: "Total Trainings", value: courses.length, color: [147, 51, 234] },
    { label: "Due Soon", value: stats?.expiringSoonCount || 0, color: [245, 158, 11] },
    { label: "Overdue", value: stats?.overdueCount || 0, color: [239, 68, 68] },
  ];
  const cardW = (usableW - 12) / 4;
  statCards.forEach((card, i) => {
    const x = margin + i * (cardW + 4);
    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(x, y, cardW, 16, 2, 2, "FD");
    doc.setFillColor(...card.color);
    doc.roundedRect(x, y, 3, 16, 2, 2, "F");
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(card.label, x + 6, y + 6);
    doc.setTextColor(...card.color);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(String(card.value), x + 6, y + 13);
  });
  y += 22;

  // ── Table ──
  const nameColW = 55;
  const colW = Math.max(14, (usableW - nameColW) / Math.min(courses.length, 20));
  const rowH = 7;
  const headerH = 18;

  const rowsPerPage = Math.floor((pageH - y - margin) / rowH);
  const totalPages = Math.max(1, Math.ceil(staff.length / rowsPerPage));

  let staffIdx = 0;
  let pageNum = 0;

  while (staffIdx < staff.length) {
    if (pageNum > 0) doc.addPage();
    pageNum++;
    drawHeader(pageNum, totalPages);

    // Reset y for subsequent pages (skip summary)
    const tableTop = pageNum === 1 ? y : 30;

    // Column headers
    doc.setFillColor(241, 245, 249);
    doc.rect(margin, tableTop, usableW, headerH, "F");
    doc.setDrawColor(226, 232, 240);
    doc.rect(margin, tableTop, usableW, headerH, "S");

    doc.setTextColor(51, 65, 85);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.text("Staff Member", margin + 3, tableTop + 6);
    doc.setFontSize(6);
    doc.setFont("helvetica", "normal");
    doc.text("Role / Home / DBS Exp", margin + 3, tableTop + 12);

    courses.forEach((c, ci) => {
      const cx = margin + nameColW + ci * colW;
      doc.saveGraphicsState();
      // rotate text for course names
      doc.text(c.course_name || c.name || "", cx + colW / 2, tableTop + headerH - 3, { align: "center", angle: 60 });
      doc.restoreGraphicsState();
    });

    let rowY = tableTop + headerH;
    const endIdx = Math.min(staffIdx + rowsPerPage, staff.length);

    for (let i = staffIdx; i < endIdx; i++) {
      const s = staff[i];

      // Row background
      if ((i - staffIdx) % 2 === 1) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, rowY, usableW, rowH, "F");
      }

      // Staff name + details
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text(s.full_name || "—", margin + 3, rowY + 3.5);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(5.5);
      doc.setTextColor(100, 116, 139);
      const role = (s.role || "").replace(/_/g, " ");
      const home = s.homeName || "—";
      const dbs = s.dbs_expiry ? format(new Date(s.dbs_expiry), "dd/MM/yy") : "—";
      doc.text(`${role} | ${home} | DBS: ${dbs}`, margin + 3, rowY + 6.5);

      // Course cells
      courses.forEach((c, ci) => {
        const cx = margin + nameColW + ci * colW;
        const record = recordMap[`${s.id}:${c.id}`];
        const status = calcTrainingStatus(record);
        const fill = STATUS_FILL[status] || [241, 245, 249];
        const textColor = STATUS_TEXT[status] || [100, 116, 139];
        const label = STATUS_SHORT[status] || "—";

        doc.setFillColor(...fill);
        doc.rect(cx + 0.5, rowY + 0.5, colW - 1, rowH - 1, "F");
        doc.setTextColor(...textColor);
        doc.setFontSize(5.5);
        doc.setFont("helvetica", "bold");
        doc.text(label, cx + colW / 2, rowY + 4, { align: "center" });
      });

      // Row border
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, rowY + rowH, margin + usableW, rowY + rowH);

      rowY += rowH;
    }

    staffIdx = endIdx;
  }

  // ── Footer / signature on last page ──
  // (handled by page header already; add legend at end)
  if (pageNum > 0) {
    doc.addPage();
    drawHeader(pageNum + 1, pageNum + 1);
    let ly = 34;
    doc.setTextColor(51, 65, 85);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Status Legend", margin, ly);
    ly += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    Object.entries(STATUS_SHORT).forEach(([key, label]) => {
      const fill = STATUS_FILL[key] || [241, 245, 249];
      doc.setFillColor(...fill);
      doc.rect(margin, ly - 3, 6, 4, "F");
      doc.text(`${label} — ${key.replace(/_/g, " ")}`, margin + 9, ly);
      ly += 6;
    });

    ly += 6;
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, ly, pageW - margin, ly);
    ly += 6;
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(`This report was generated on ${dateStr} by ${generatedBy?.name || "System"}${generatedBy?.role ? ` (${generatedBy.role})` : ""}.`, margin, ly);
    doc.text("This document reflects the training compliance status as recorded in the system at the time of generation.", margin, ly + 4);
    ly += 12;
    doc.text("Signature: _______________________________", margin, ly);
    doc.text(`Date: ${format(generatedAt, "d MMM yyyy")}`, margin + 100, ly);
  }

  const filename = `Training_Matrix_Report_${format(generatedAt, "yyyy-MM-dd_HHmm")}.pdf`;
  doc.save(filename);
}