import { useMemo } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Printer } from "lucide-react";
import { format } from "date-fns";
import { calcTrainingStatus } from "@/components/staff/training/TrainingStatusBadge";

const STATUS_LABELS = {
  completed: "Completed",
  valid: "Valid",
  expiring_soon: "Due Soon",
  expired: "Overdue",
  not_started: "Not Started",
  in_progress: "In Progress",
  na: "N/A",
};

const STATUS_CELL_CLASS = {
  completed: "bg-green-100 text-green-700 border-green-300",
  valid: "bg-green-100 text-green-700 border-green-300",
  expiring_soon: "bg-amber-100 text-amber-700 border-amber-300",
  expired: "bg-red-100 text-red-700 border-red-300",
  not_started: "bg-blue-50 text-blue-600 border-blue-200",
  in_progress: "bg-blue-50 text-blue-600 border-blue-200",
  na: "bg-slate-100 text-slate-400 border-slate-200",
};

export default function TrainingReportModal({
  open,
  onOpenChange,
  staff,
  courses,
  recordMap,
  stats,
  filters = {},
  generatedBy,
}) {
  const generatedAt = useMemo(() => new Date(), [open]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-[1100px] w-[95vw] max-h-[92vh] overflow-hidden flex flex-col p-0 print:max-w-none print:w-full print:max-h-none print:overflow-visible print:rounded-none print:border-0">
        <DialogHeader className="px-6 py-4 border-b border-slate-200 flex-row items-center justify-between space-y-0 print:hidden">
          <DialogTitle className="text-base font-bold text-slate-900">
            Training Matrix Report Preview
          </DialogTitle>
          <div className="flex items-center gap-2 pr-8">
            <Button size="sm" className="gap-1.5" onClick={handlePrint}>
              <Printer className="w-4 h-4" />
              Print
            </Button>
          </div>
        </DialogHeader>

        <div className="overflow-y-auto flex-1 bg-slate-100 print:overflow-visible print:bg-white">
          {/* ── Report Document ── */}
          <div className="training-report mx-auto bg-white shadow-lg print:shadow-none" id="training-report-print-area">
            {/* Header Bar */}
            <div className="bg-blue-800 text-white px-8 py-4 print:px-6 print:py-3">
              <h1 className="text-xl font-bold">Training Matrix Compliance Report</h1>
              <div className="flex items-center gap-6 mt-1 text-xs">
                <span>Generated: {format(generatedAt, "d MMMM yyyy 'at' HH:mm")}</span>
                <span>Generated by: {generatedBy?.name || "System"}{generatedBy?.role ? ` (${generatedBy.role})` : ""}</span>
              </div>
            </div>

            {/* Report Scope */}
            <div className="px-8 py-4 print:px-6">
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-4">
                <p className="text-xs font-bold text-slate-700 mb-2">Report Scope</p>
                <div className="grid grid-cols-2 gap-x-8 gap-y-1 text-xs text-slate-600">
                  <p><span className="font-semibold text-slate-700">Home:</span> {filters.home || "All Homes"}</p>
                  <p><span className="font-semibold text-slate-700">Department:</span> {filters.department || "All Departments"}</p>
                  <p><span className="font-semibold text-slate-700">Role:</span> {filters.role || "All Roles"}</p>
                  <p><span className="font-semibold text-slate-700">Search:</span> {filters.search ? `"${filters.search}"` : "—"}</p>
                </div>
              </div>
            </div>

            {/* Summary Stats */}
            <div className="px-8 pb-4 print:px-6">
              <div className="grid grid-cols-4 gap-3">
                <StatCard label="Total Staff" value={staff.length} color="blue" />
                <StatCard label="Total Trainings" value={courses.length} color="purple" />
                <StatCard label="Due Soon" value={stats?.expiringSoonCount || 0} color="amber" />
                <StatCard label="Overdue" value={stats?.overdueCount || 0} color="red" />
              </div>
            </div>

            {/* Matrix Table — courses as rows, staff as columns */}
            <div className="px-8 pb-6 print:px-6">
              <div className="overflow-x-auto print:overflow-visible">
                <table className="w-full border-collapse text-[10px]">
                  <thead>
                    <tr className="bg-slate-100 border border-slate-200">
                      <th className="text-left py-2 px-3 font-bold text-slate-700 sticky left-0 bg-slate-100 z-10 min-w-[180px] print:static">
                        Training Module
                      </th>
                      {staff.map(s => (
                        <th key={s.id} className="px-1 py-2 min-w-[90px] max-w-[110px] align-top text-center">
                          <div className="flex flex-col items-center gap-0.5">
                            <div className="font-semibold text-[10px] text-slate-800 leading-tight">{s.full_name}</div>
                            <div className="text-[8px] text-slate-400 leading-tight">{(s.role || "").replace(/_/g, " ")}</div>
                            <div className="text-[8px] text-slate-500 leading-tight">
                              <span>Joined: {s.start_date ? format(new Date(s.start_date), "dd/MM/yy") : "—"}</span>
                            </div>
                            <div className="text-[8px] text-slate-500 leading-tight">
                              <span>DBS: {s.dbs_issue_date ? format(new Date(s.dbs_issue_date), "dd/MM/yy") : "—"}</span>
                            </div>
                            <div className={`text-[8px] font-medium leading-tight ${
                              s.dbs_expiry && new Date(s.dbs_expiry) < new Date() ? "text-red-600" :
                              s.dbs_expiry && new Date(s.dbs_expiry) < new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) ? "text-amber-600" :
                              "text-slate-500"
                            }`}>
                              Exp: {s.dbs_expiry ? format(new Date(s.dbs_expiry), "dd/MM/yy") : "—"}
                            </div>
                          </div>
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {courses.map((course, cIdx) => (
                      <tr key={course.id} className={cIdx % 2 === 1 ? "bg-slate-50/50" : "bg-white"}>
                        <td className="py-1.5 px-3 border-b border-slate-100 font-medium text-slate-700 sticky left-0 z-10 print:static" style={{ background: cIdx % 2 === 1 ? "#f8fafc" : "#ffffff" }}>
                          <div className="text-[10px] leading-tight">{course.course_name || course.name}</div>
                          {course.is_mandatory && (
                            <span className="text-[8px] text-red-500 font-semibold">Mandatory</span>
                          )}
                        </td>
                        {staff.map(s => {
                          const record = recordMap[`${s.id}:${course.id}`];
                          const status = calcTrainingStatus(record);
                          return (
                            <td key={s.id} className="py-1 px-1 border-b border-slate-100 text-center align-top">
                              <div className={`text-[8px] font-bold px-1 py-1 rounded border ${STATUS_CELL_CLASS[status]}`}>
                                {STATUS_LABELS[status]}
                              </div>
                            </td>
                          );
                        })}
                      </tr>
                    ))}
                    {staff.length === 0 && (
                      <tr>
                        <td colSpan={courses.length + 1} className="text-center py-8 text-slate-400 text-xs">
                          No staff data available for the selected filters.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Legend & Footer */}
            <div className="px-8 pb-8 print:px-6">
              <div className="border-t border-slate-200 pt-4">
                <p className="text-xs font-bold text-slate-700 mb-2">Status Legend</p>
                <div className="flex flex-wrap gap-3 mb-4">
                  {Object.entries(STATUS_LABELS).map(([key, label]) => (
                    <div key={key} className="flex items-center gap-1.5">
                      <span className={`inline-block w-4 h-4 rounded border ${STATUS_CELL_CLASS[key]}`} />
                      <span className="text-[10px] text-slate-600">{label}</span>
                    </div>
                  ))}
                </div>
                <div className="border-t border-slate-200 pt-3 text-[9px] text-slate-500 space-y-1">
                  <p>This report was generated on {format(generatedAt, "d MMMM yyyy 'at' HH:mm")} by {generatedBy?.name || "System"}{generatedBy?.role ? ` (${generatedBy.role})` : ""}.</p>
                  <p>This document reflects the training compliance status as recorded in the system at the time of generation.</p>
                  <div className="flex gap-16 mt-4">
                    <p>Signature: _______________________________</p>
                    <p>Date: {format(generatedAt, "d MMM yyyy")}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function StatCard({ label, value, color }) {
  const colorMap = {
    blue: "border-l-blue-500 text-blue-600",
    purple: "border-l-purple-500 text-purple-600",
    amber: "border-l-amber-500 text-amber-600",
    red: "border-l-red-500 text-red-600",
  };
  return (
    <div className={`bg-white border border-slate-200 border-l-4 rounded-lg p-3 ${colorMap[color]}`}>
      <p className="text-[10px] text-slate-500 font-medium">{label}</p>
      <p className="text-2xl font-black">{value}</p>
    </div>
  );
}